export const categories = [
  {
    id: "11",
    resName: "citybalcony",
    name: "الفطور",
    name2: "Breakfast",
    img: "./images/menu/brakfast.jpg",
  },
  {
    id: "12",
    resName: "citybalcony",
    name: "سلطات",
    name2: "Salad",
    img: "./images/menu/salat.jpg",
  },
  {
    id: "13",
    resName: "citybalcony",
    name: "مقبلات",
    name2: "Appetizers",
    img: "./images/menu/appetizers.jpg",
  },
  {
    id: "14",
    resName: "citybalcony",
    name: "الغداء/العشاء",
    name2: "Lunch/dinner",
    img: "./images/menu/lunchdinner.jpg",
  },
  {
    id: "15",
    resName: "citybalcony",
    name: "سناكات",
    name2: "Snacks",
    img: "./images/menu/snacks.jpg",
  },
  {
    id: "16",
    resName: "citybalcony",
    name: "الشوربات",
    name2: "Soups",
    img: "./images/menu/soups.jpg",
  },
  {
    id: "17",
    resName: "citybalcony",
    name: "الحلويات",
    name2: "Desserts",
    img: "./images/menu/desserts.jpg",
  },
  {
    id: "18",
    resName: "citybalcony",
    name: "ايس كريم",
    name2: "Ice Cream",
    img: "./images/menu/iceCream.jpg",
  },
  {
    id: "19",
    resName: "citybalcony",
    name: "المشروبات الساخنة",
    name2: "Hot Drinks",
    img: "./images/menu/hotDrinks.jpg",
  },
  {
    id: "20",
    resName: "citybalcony",
    name: "الشاي",
    name2: "Tea",
    img: "./images/menu/tea.jpg",
  },
  {
    id: "21",
    resName: "citybalcony",
    name: "العصائر الطبيعية",
    name2: "Fresh Juices",
    img: "./images/menu/freshJuices.jpg",
  },
  {
    id: "22",
    resName: "citybalcony",
    name: "مشروبات غازية",
    name2: "Soft drinks",
    img: "./images/menu/softdrinks.jpg",
  },
  {
    id: "23",
    resName: "citybalcony",
    name: "موهيتو",
    name2: "Mojito",
    img: "./images/menu/mojito.jpg",
  },
  {
    id: "24",
    resName: "citybalcony",
    name: "ميلك شيك",
    name2: "Milkshake",
    img: "./images/menu/milkshake.jpg",
  },
  {
    id: "25",
    resName: "citybalcony",
    name: "كوكتيلات",
    name2: "Cocktails",
    img: "./images/menu/cocktails.jpg",
  },
  {
    id: "26",
    resName: "citybalcony",
    name: "سموذي",
    name2: "Smoothie",
    img: "./images/menu/smoothie.jpg",
  },
  {
    id: "27",
    resName: "citybalcony",
    name: "مشروبات باردة",
    name2: "Iced Coffee",
    img: "./images/menu/icedCoffee.jpg",
  },
  {
    id: "28",
    resName: "citybalcony",
    name: "اراجيل",
    name2: "Sheshah",
    img: "./images/menu/sheshah.jpg",
  },
];
